# Generated by Django 3.2 on 2023-11-23 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя содержит недопустимый символ!', regex='^[\\\\w.@+-]+\\\\Z')], verbose_name='Имя пользователя'),
        ),
    ]
